name: Deploy to Dev

on:
  push:
      paths-ignore:
        - .github/**
      branches:
        - dev
  workflow_dispatch: # 👈 This adds the manual "Run workflow" button in GitHub

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      target_ws: dev
    secrets:
      databricks_host: ${{ secrets.DEV_DEPLOY_URL }}
      databricks_token: ${{ secrets.DEV_DEPLOY_TOKEN }}